import type { Metadata } from "next";
import "./globals.css";
import ClinetLayout from "./ClientLayout";
import localFont from "next/font/local";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { ThemeProvider } from "../components/ui/custom/DarkMode";
import { Toaster } from "sonner";

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "./../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${pretendard.variable}`}
      suppressHydrationWarning
    >
      <body className={`min-h-[100dvh] flex flex-col ${pretendard.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClinetLayout>
            {children}
            <Toaster richColors />
          </ClinetLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
