server:
  port: 8080
  shutdown: graceful
  tomcat:
    max-swallow-size: 1GB
    max-http-form-post-size: 1GB

spring:
  output:
    ansi:
      enabled: always

  profiles:
    active: dev
    include: secret

  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: ${spring.servlet.multipart.max-request-size}

  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: "${spring.security.oauth2.client.registration.kakao.clientId}"
            client-secret: "${spring.security.oauth2.client.registration.kakao.client-secret}"
            client-authentication-method: client_secret_post
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "${custom.site.backUrl}/login/oauth2/code/kakao"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: DEBUG
    org.springframework.transaction.interceptor: DEBUG

springdoc:
  default-produces-media-type: application/json;charset=UTF-8


custom:
  appName: test-app
  prod:
    domain: dooafjbdf.shop
    backUrl: "https://api.${custom.appName}.${custom.prod.domain}"
    frontUrl: "https://www.${custom.appName}.${custom.prod.domain}"

  dev:
    domain: localhost
    backUrl: "http://${custom.dev.domain}:${server.port}"
    frontUrl: "http://${custom.dev.domain}:3000"

  site:
    domain: "${custom.dev.domain}"
    backUrl: "${custom.dev.backUrl}"
    frontUrl: "${custom.dev.frontUrl}"

  jwt:
    expire-seconds: "#{60 * 30}"
  genFile:
    dirPath: c:/temp/glog_dev